//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HalloWorld", ReplyAction="http://tempuri.org/IService1/HalloWorldResponse")]
        string HalloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HalloWorld", ReplyAction="http://tempuri.org/IService1/HalloWorldResponse")]
        System.Threading.Tasks.Task<string> HalloWorldAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference.IService1>, Client.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HalloWorld() {
            return base.Channel.HalloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HalloWorldAsync() {
            return base.Channel.HalloWorldAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.TestName")]
    public interface TestName {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestName/HalloWorld2", ReplyAction="http://tempuri.org/TestName/HalloWorld2Response")]
        string HalloWorld2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestName/HalloWorld2", ReplyAction="http://tempuri.org/TestName/HalloWorld2Response")]
        System.Threading.Tasks.Task<string> HalloWorld2Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TestNameChannel : Client.ServiceReference.TestName, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestNameClient : System.ServiceModel.ClientBase<Client.ServiceReference.TestName>, Client.ServiceReference.TestName {
        
        public TestNameClient() {
        }
        
        public TestNameClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestNameClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestNameClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestNameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HalloWorld2() {
            return base.Channel.HalloWorld2();
        }
        
        public System.Threading.Tasks.Task<string> HalloWorld2Async() {
            return base.Channel.HalloWorld2Async();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ITestConfigurationName")]
    public interface ITestConfigurationName {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestConfigurationName/HalloWorld3", ReplyAction="http://tempuri.org/ITestConfigurationName/HalloWorld3Response")]
        string HalloWorld3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestConfigurationName/HalloWorld3", ReplyAction="http://tempuri.org/ITestConfigurationName/HalloWorld3Response")]
        System.Threading.Tasks.Task<string> HalloWorld3Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestConfigurationNameChannel : Client.ServiceReference.ITestConfigurationName, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestConfigurationNameClient : System.ServiceModel.ClientBase<Client.ServiceReference.ITestConfigurationName>, Client.ServiceReference.ITestConfigurationName {
        
        public TestConfigurationNameClient() {
        }
        
        public TestConfigurationNameClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestConfigurationNameClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestConfigurationNameClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestConfigurationNameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HalloWorld3() {
            return base.Channel.HalloWorld3();
        }
        
        public System.Threading.Tasks.Task<string> HalloWorld3Async() {
            return base.Channel.HalloWorld3Async();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ITestCallbackContract", CallbackContract=typeof(Client.ServiceReference.ITestCallbackContractCallback))]
    public interface ITestCallbackContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestCallbackContract/HalloWorld4", ReplyAction="http://tempuri.org/ITestCallbackContract/HalloWorld4Response")]
        string HalloWorld4();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestCallbackContract/HalloWorld4", ReplyAction="http://tempuri.org/ITestCallbackContract/HalloWorld4Response")]
        System.Threading.Tasks.Task<string> HalloWorld4Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestCallbackContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITestCallbackContract/onTextCallback")]
        void onTextCallback(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestCallbackContractChannel : Client.ServiceReference.ITestCallbackContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestCallbackContractClient : System.ServiceModel.DuplexClientBase<Client.ServiceReference.ITestCallbackContract>, Client.ServiceReference.ITestCallbackContract {
        
        public TestCallbackContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TestCallbackContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TestCallbackContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TestCallbackContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TestCallbackContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string HalloWorld4() {
            return base.Channel.HalloWorld4();
        }
        
        public System.Threading.Tasks.Task<string> HalloWorld4Async() {
            return base.Channel.HalloWorld4Async();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ITestSessionMode", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ITestSessionMode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSessionMode/HalloWorld5", ReplyAction="http://tempuri.org/ITestSessionMode/HalloWorld5Response")]
        string HalloWorld5();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSessionMode/HalloWorld5", ReplyAction="http://tempuri.org/ITestSessionMode/HalloWorld5Response")]
        System.Threading.Tasks.Task<string> HalloWorld5Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSessionMode/HalloWorld6", ReplyAction="http://tempuri.org/ITestSessionMode/HalloWorld6Response")]
        string HalloWorld6();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestSessionMode/HalloWorld6", ReplyAction="http://tempuri.org/ITestSessionMode/HalloWorld6Response")]
        System.Threading.Tasks.Task<string> HalloWorld6Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestSessionModeChannel : Client.ServiceReference.ITestSessionMode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestSessionModeClient : System.ServiceModel.ClientBase<Client.ServiceReference.ITestSessionMode>, Client.ServiceReference.ITestSessionMode {
        
        public TestSessionModeClient() {
        }
        
        public TestSessionModeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestSessionModeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestSessionModeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestSessionModeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HalloWorld5() {
            return base.Channel.HalloWorld5();
        }
        
        public System.Threading.Tasks.Task<string> HalloWorld5Async() {
            return base.Channel.HalloWorld5Async();
        }
        
        public string HalloWorld6() {
            return base.Channel.HalloWorld6();
        }
        
        public System.Threading.Tasks.Task<string> HalloWorld6Async() {
            return base.Channel.HalloWorld6Async();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ITestProtectionLevel")]
    public interface ITestProtectionLevel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestProtectionLevel/HalloWorld7", ReplyAction="http://tempuri.org/ITestProtectionLevel/HalloWorld7Response")]
        string HalloWorld7();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestProtectionLevel/HalloWorld7", ReplyAction="http://tempuri.org/ITestProtectionLevel/HalloWorld7Response")]
        System.Threading.Tasks.Task<string> HalloWorld7Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestProtectionLevelChannel : Client.ServiceReference.ITestProtectionLevel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestProtectionLevelClient : System.ServiceModel.ClientBase<Client.ServiceReference.ITestProtectionLevel>, Client.ServiceReference.ITestProtectionLevel {
        
        public TestProtectionLevelClient() {
        }
        
        public TestProtectionLevelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestProtectionLevelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestProtectionLevelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestProtectionLevelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HalloWorld7() {
            return base.Channel.HalloWorld7();
        }
        
        public System.Threading.Tasks.Task<string> HalloWorld7Async() {
            return base.Channel.HalloWorld7Async();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Ybao", ConfigurationName="ServiceReference.ITestNameNamespace")]
    public interface ITestNameNamespace {
        
        [System.ServiceModel.OperationContractAttribute(Action="Ybao/ITestNameNamespace/HalloWorld", ReplyAction="Ybao/ITestNameNamespace/HalloWorldResponse")]
        string HalloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="Ybao/ITestNameNamespace/HalloWorld", ReplyAction="Ybao/ITestNameNamespace/HalloWorldResponse")]
        System.Threading.Tasks.Task<string> HalloWorldAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestNameNamespaceChannel : Client.ServiceReference.ITestNameNamespace, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestNameNamespaceClient : System.ServiceModel.ClientBase<Client.ServiceReference.ITestNameNamespace>, Client.ServiceReference.ITestNameNamespace {
        
        public TestNameNamespaceClient() {
        }
        
        public TestNameNamespaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestNameNamespaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestNameNamespaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestNameNamespaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HalloWorld() {
            return base.Channel.HalloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HalloWorldAsync() {
            return base.Channel.HalloWorldAsync();
        }
    }
}
